name:    carte-rest
version: "0.0.0"

dependencies:
- aeson
- base
- uuid
- yesod-core

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  carte-rest:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - carte-rest
